### ISSUE TITLE
Mouse hover minimap

### ISSUE THREAD

**Issue by camHQ** [esthorace/python-theme#1]
Python Theme v2.0.9

Hello,

When hovering over the minimap with the mouse cursor, the rectangle that appears is opaque, but it should be transparent !
Thank you for everything.

![Peek 08-11-2024 13-08](https://github.com/user-attachments/assets/bf4e4910-8ea8-47f1-8144-6d60fc84c38e)

**Comment by esthorace** [comment]
Thank you very much for the observation. It is now resolved. Any suggestions are welcome!
